/*! @license Firebase v3.7.5
    Build: 3.7.5-rc.1
    Terms: https://firebase.google.com/terms/ */
var firebase = null; (function() { var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},l=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},n=ba(this),ca=function(a,b){if(b)a:{var c=n;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&l(c,a,{configurable:!0,writable:!0,value:b})}};
ca("Symbol",function(a){if(a)return a;var b=function(g,k){this.W=g;l(this,"description",{configurable:!0,writable:!0,value:k})};b.prototype.toString=function(){return this.W};var c="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",d=0,e=function(g){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(g||"")+"_"+d++,g)};return e});
var p=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");},q=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c},da=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var r=this||self,ea=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}},u=function(a,b){function c(){}c.prototype=b.prototype;a.ia=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(d,e,g){for(var k=Array(arguments.length-2),f=2;f<arguments.length;f++)k[f-2]=arguments[f];return b.prototype[e].apply(d,k)}};var v=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?function(a){return a&&AsyncContext.Snapshot.wrap(a)}:function(a){return a};function w(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,w);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)}u(w,Error);w.prototype.name="CustomError";function x(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");w.call(this,c+a[d])}u(x,w);x.prototype.name="AssertionError";function z(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var g=d}else a&&(e+=": "+a,g=b);throw new x(""+e,g||[]);}
var A=function(a,b,c){a||z("",null,b,Array.prototype.slice.call(arguments,2))},fa=function(a,b,c){a==null&&z("Expected to exist: %s.",[a],b,Array.prototype.slice.call(arguments,2));return a},B=function(a,b,c){if(typeof a!=="function"){var d=typeof a;d=d!="object"?d:a?Array.isArray(a)?"array":d:"null";z("Expected function but got %s: %s.",[d,a],b,Array.prototype.slice.call(arguments,2))}};var C=function(a,b){this.ba=100;this.X=a;this.da=b;this.G=0;this.F=null};C.prototype.get=function(){if(this.G>0){this.G--;var a=this.F;this.F=a.next;a.next=null}else a=this.X();return a};C.prototype.put=function(a){this.da(a);this.G<this.ba&&(this.G++,a.next=this.F,this.F=a)};function ha(a){r.setTimeout(function(){throw a;},0)};var D=function(){this.H=this.o=null};D.prototype.add=function(a,b){var c=ia.get();c.set(a,b);this.H?this.H.next=c:(A(!this.o),this.o=c);this.H=c};D.prototype.remove=function(){var a=null;this.o&&(a=this.o,this.o=this.o.next,this.o||(this.H=null),a.next=null);return a};var ia=new C(function(){return new E},function(a){return a.reset()}),E=function(){this.next=this.scope=this.fn=null};E.prototype.set=function(a,b){this.fn=a;this.scope=b;this.next=null};
E.prototype.reset=function(){this.next=this.scope=this.fn=null};var F=r.console&&r.console.createTask?r.console.createTask.bind(r.console):void 0,G=F?Symbol("consoleTask"):void 0;
function H(a,b){function c(){var f=da.apply(0,arguments),h=this;return k.run(function(){return a.call.apply(a,[h].concat(f instanceof Array?f:q(p(f))))})}b=b===void 0?"anonymous":b;if(G&&a[G])return a;var d=a,e,g=(e=ja)==null?void 0:e();a=function(){var f=da.apply(0,arguments),h,m=(h=ja)==null?void 0:h();if(g!==m)throw Error(b+" was scheduled in '"+g+"' but called in '"+m+"'.\nMake sure your test awaits all async calls.\n\nTIP: To help investigate, debug the test in Chrome and look at the async portion\nof the call stack to see what originally scheduled the callback.  Then, make the\ntest wait for the relevant asynchronous work to finish.");return d.call.apply(d,
[this].concat(f instanceof Array?f:q(p(f))))};if(!F)return a;var k=F(a.name||b);c[fa(G)]=k;return c}var ja;var I,J=!1,ka=new D,K=function(a,b){a=H(a,"goog.async.run");I||la();J||(I(),J=!0);ka.add(a,b)},la=function(){var a=Promise.resolve(void 0);I=function(){a.then(ma)}};function ma(){for(var a;a=ka.remove();){try{a.fn.call(a.scope)}catch(b){ha(b)}ia.put(a)}J=!1};var L=function(){};var O=function(a,b){this.g=0;this.U=void 0;this.u=this.i=this.m=null;this.D=this.I=!1;if(a!=L)try{var c=this;a.call(b,function(d){M(c,2,d)},function(d){if(!(d instanceof N))try{if(d instanceof Error)throw d;throw Error("Promise rejected.");}catch(e){}M(c,3,d)})}catch(d){M(this,3,d)}},na=function(){this.next=this.context=this.v=this.l=this.child=null;this.A=!1};na.prototype.reset=function(){this.context=this.v=this.l=this.child=null;this.A=!1};
var oa=new C(function(){return new na},function(a){a.reset()}),pa=function(a,b,c){var d=oa.get();d.l=a;d.v=b;d.context=c;return d},ra=function(a,b,c){qa(a,b,c,null)||K(ea(b,a))};O.prototype.then=function(a,b,c){a!=null&&B(a,"opt_onFulfilled should be a function.");b!=null&&B(b,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");return sa(this,v(typeof a==="function"?a:null),v(typeof b==="function"?b:null),c)};O.prototype.$goog_Thenable=!0;
var ua=function(a,b,c,d){b!=null&&B(b,"opt_onFulfilled should be a function.");c!=null&&B(c,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");ta(a,pa(b||L,c||null,d))};O.prototype.finally=function(a){var b=this;a=v(a);return new O(function(c,d){ua(b,function(e){a();c(e)},function(e){a();d(e)})})};O.prototype.V=function(a,b){return sa(this,null,v(a),b)};O.prototype.catch=O.prototype.V;
O.prototype.cancel=function(a){if(this.g==0){var b=new N(a);K(function(){va(this,b)},this)}};
var va=function(a,b){if(a.g==0)if(a.m){var c=a.m;if(c.i){for(var d=0,e=null,g=null,k=c.i;k&&(k.A||(d++,k.child==a&&(e=k),!(e&&d>1)));k=k.next)e||(g=k);e&&(c.g==0&&d==1?va(c,b):(g?(d=g,A(c.i),A(d!=null),d.next==c.u&&(c.u=d),d.next=d.next.next):wa(c),xa(c,e,3,b)))}a.m=null}else M(a,3,b)},ta=function(a,b){a.i||a.g!=2&&a.g!=3||ya(a);A(b.l!=null);a.u?a.u.next=b:a.i=b;a.u=b},sa=function(a,b,c,d){b&&(b=H(b,"goog.Promise.then"));c&&(c=H(c,"goog.Promise.then"));var e=pa(null,null,null);e.child=new O(function(g,
k){e.l=b?function(f){try{var h=b.call(d,f);g(h)}catch(m){k(m)}}:g;e.v=c?function(f){try{var h=c.call(d,f);h===void 0&&f instanceof N?k(f):g(h)}catch(m){k(m)}}:k});e.child.m=a;ta(a,e);return e.child};O.prototype.fa=function(a){A(this.g==1);this.g=0;M(this,2,a)};O.prototype.ga=function(a){A(this.g==1);this.g=0;M(this,3,a)};
var M=function(a,b,c){a.g==0&&(a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.g=1,qa(c,a.fa,a.ga,a)||(a.U=c,a.g=b,a.m=null,ya(a),b!=3||c instanceof N||za(a,c)))},qa=function(a,b,c,d){if(a instanceof O)return ua(a,b,c,d),!0;if(a)try{var e=!!a.$goog_Thenable}catch(k){e=!1}else e=!1;if(e)return a.then(b,c,d),!0;e=typeof a;if(e=="object"&&a!=null||e=="function")try{var g=a.then;if(typeof g==="function")return Aa(a,g,b,c,d),!0}catch(k){return c.call(d,k),!0}return!1},Aa=function(a,
b,c,d,e){var g=!1,k=function(h){g||(g=!0,c.call(e,h))},f=function(h){g||(g=!0,d.call(e,h))};try{b.call(a,k,f)}catch(h){f(h)}},ya=function(a){a.I||(a.I=!0,K(a.Y,a))},wa=function(a){var b=null;a.i&&(b=a.i,a.i=b.next,b.next=null);a.i||(a.u=null);b!=null&&A(b.l!=null);return b};O.prototype.Y=function(){for(var a;a=wa(this);)xa(this,a,this.g,this.U);this.I=!1};
var xa=function(a,b,c,d){if(c==3&&b.v&&!b.A)for(;a&&a.D;a=a.m)a.D=!1;if(b.child)b.child.m=null,Ba(b,c,d);else try{b.A?b.l.call(b.context):Ba(b,c,d)}catch(e){Ca.call(null,e)}oa.put(b)},Ba=function(a,b,c){b==2?a.l.call(a.context,c):a.v&&a.v.call(a.context,c)},za=function(a,b){a.D=!0;K(function(){a.D&&Ca.call(null,b)})},Ca=ha,N=function(a){w.call(this,a)};u(N,w);N.prototype.name="cancel";O.all=function(a){return new O(function(b,c){var d=a.length,e=[];if(d)for(var g=function(m,t){d--;e[m]=t;d==0&&b(e)},k=function(m){c(m)},f,h=0;h<a.length;h++)f=a[h],ra(f,ea(g,h),k);else b(e)})};O.resolve=function(a){if(a instanceof O)return a;var b=new O(L);M(b,2,a);return b};O.reject=function(a){return new O(function(b,c){c(a)})};O.prototype["catch"]=O.prototype.V;var P=O;typeof Promise!=="undefined"&&(P=Promise);function Q(a,b){if(!(b instanceof Object))return b;switch(b.constructor){case Date:return new Date(b.getTime());case Object:a===void 0&&(a={});break;case Array:a=[];break;default:return b}for(var c in b)b.hasOwnProperty(c)&&(a[c]=Q(a[c],b[c]));return a};var Da=Error.captureStackTrace,S=function(a,b){this.code=a;this.message=b;if(Da)Da(this,R.prototype.create);else{var c=Error.apply(this,arguments);this.name="FirebaseError";Object.defineProperty(this,"stack",{get:function(){return c.stack}})}};S.prototype.constructor=S;S.prototype.name="FirebaseError";var R=function(a,b,c){this.service=a;this.ea=b;this.errors=c;this.pattern=/\{\$([^}]+)}/g};
R.prototype.create=function(a,b){b===void 0&&(b={});var c=this.errors[a];a=this.service+"/"+a;c=c===void 0?"Error":c.replace(this.pattern,function(e,g){e=b[g];return e!==void 0?e.toString():"<"+g+"?>"});c=this.ea+": "+c+" ("+a+").";c=new S(a,c);for(var d in b)b.hasOwnProperty(d)&&d.slice(-1)!=="_"&&(c[d]=b[d]);return c};var Ea=P;function Fa(a,b){a=new T(a,b);return a.subscribe.bind(a)}var T=function(a,b){var c=this;this.h=[];this.T=0;this.task=Ea.resolve();this.B=!1;this.K=b;this.task.then(function(){a(c)}).catch(function(d){c.error(d)})};T.prototype.next=function(a){U(this,function(b){b.next(a)})};T.prototype.error=function(a){U(this,function(b){b.error(a)});this.close(a)};T.prototype.complete=function(){U(this,function(a){a.complete()});this.close()};
T.prototype.subscribe=function(a,b,c){var d=this;if(a===void 0&&b===void 0&&c===void 0)throw Error("Missing Observer.");var e=Ga(a)?a:{next:a,error:b,complete:c};e.next===void 0&&(e.next=V);e.error===void 0&&(e.error=V);e.complete===void 0&&(e.complete=V);a=this.ha.bind(this,this.h.length);this.B&&this.task.then(function(){try{d.P?e.error(d.P):e.complete()}catch(g){}});this.h.push(e);return a};
T.prototype.ha=function(a){this.h!==void 0&&this.h[a]!==void 0&&(delete this.h[a],--this.T,this.T===0&&this.K!==void 0&&this.K(this))};var U=function(a,b){if(!a.B)for(var c=0;c<a.h.length;c++)Ha(a,c,b)},Ha=function(a,b,c){a.task.then(function(){if(a.h!==void 0&&a.h[b]!==void 0)try{c(a.h[b])}catch(d){typeof console!=="undefined"&&console.error&&console.error(d)}})};T.prototype.close=function(a){var b=this;this.B||(this.B=!0,a!==void 0&&(this.P=a),this.task.then(function(){b.h=void 0;b.K=void 0}))};
function Ga(a){if(typeof a!=="object"||a===null)return!1;for(var b=p(["next","error","complete"]),c=b.next();!c.done;c=b.next())if(c=c.value,c in a&&typeof a[c]==="function")return!0;return!1}function V(){};var W=P,X=function(a,b,c){var d=this;this.R=c;this.S=!1;this.j={};this.J=b;this.M=Q(void 0,a);a="serviceAccount"in this.M;("credential"in this.M||a)&&typeof console!=="undefined"&&console.log("The '"+(a?"serviceAccount":"credential")+"' property specified in the first argument to initializeApp() is deprecated and will be removed in the next major version. You should instead use the 'firebase-admin' package. See https://firebase.google.com/docs/admin/setup for details on how to get started.");Object.keys(c.INTERNAL.factories).forEach(function(e){var g=
c.INTERNAL.useAsService(d,e);g!==null&&(g=d.aa.bind(d,g),d[e]=g)})};X.prototype.delete=function(){var a=this;return(new W(function(b){Y(a);b()})).then(function(){a.R.INTERNAL.removeApp(a.J);var b=[];Object.keys(a.j).forEach(function(c){Object.keys(a.j[c]).forEach(function(d){b.push(a.j[c][d])})});return W.all(b.filter(function(c){return"INTERNAL"in c}).map(function(c){return c.INTERNAL.delete()}))}).then(function(){a.S=!0;a.j={}})};
X.prototype.aa=function(a,b){Y(this);typeof this.j[a]==="undefined"&&(this.j[a]={});var c=b||"[DEFAULT]";return typeof this.j[a][c]==="undefined"?(b=this.R.INTERNAL.factories[a](this,this.Z.bind(this),b),this.j[a][c]=b):this.j[a][c]};X.prototype.Z=function(a){Q(this,a)};var Y=function(a){a.S&&Z("app-deleted",{name:a.J})};n.Object.defineProperties(X.prototype,{name:{configurable:!0,enumerable:!0,get:function(){Y(this);return this.J}},options:{configurable:!0,enumerable:!0,get:function(){Y(this);return this.M}}});
X.prototype.name&&X.prototype.options||X.prototype.delete||console.log("dc");
function Ia(){function a(f){f=f||"[DEFAULT]";var h=d[f];h===void 0&&Z("no-app",{name:f});return h}function b(f,h){Object.keys(e).forEach(function(m){m=c(f,m);if(m!==null&&g[m])g[m](h,f)})}function c(f,h){if(h==="serverAuth")return null;var m=h;f=f.options;h==="auth"&&(f.serviceAccount||f.credential)&&(m="serverAuth","serverAuth"in e||Z("sa-not-supported"));return m}var d={},e={},g={},k={__esModule:!0,initializeApp:function(f,h){h===void 0?h="[DEFAULT]":(typeof h!=="string"||h==="")&&Z("bad-app-name",
{name:h+""});d[h]!==void 0&&Z("duplicate-app",{name:h});f=new X(f,h,k);d[h]=f;b(f,"create");f.INTERNAL!=void 0&&f.INTERNAL.getToken!=void 0||Q(f,{INTERNAL:{getUid:function(){return null},getToken:function(){return W.resolve(null)},addAuthTokenListener:function(){},removeAuthTokenListener:function(){}}});return f},app:a,apps:null,Promise:W,SDK_VERSION:"0.0.0",INTERNAL:{registerService:function(f,h,m,t,Ja){e[f]&&Z("duplicate-service",{name:f});e[f]=Ja?h:function(y,Ka){return h(y,Ka,"[DEFAULT]")};t&&
(g[f]=t);t=function(y){y===void 0&&(y=a());typeof y[f]!=="function"&&Z("invalid-app-argument",{name:f});return y[f]()};m!==void 0&&Q(t,m);return k[f]=t},createFirebaseNamespace:Ia,extendNamespace:function(f){Q(k,f)},createSubscribe:Fa,ErrorFactory:R,removeApp:function(f){b(d[f],"delete");delete d[f]},factories:e,useAsService:c,Promise:O,deepExtend:Q}};k["default"]=k;Object.defineProperty(k,"apps",{get:function(){return Object.keys(d).map(function(f){return d[f]})}});a.App=X;return k}
function Z(a,b){throw La.create(a,b);}
var La=new R("app","Firebase",{"no-app":"No Firebase App '{$name}' has been created - call Firebase App.initializeApp()","bad-app-name":"Illegal App name: '{$name}","duplicate-app":"Firebase App named '{$name}' already exists","app-deleted":"Firebase App named '{$name}' already deleted","duplicate-service":"Firebase service named '{$name}' already registered","sa-not-supported":"Initializing the Firebase SDK with a service account is only allowed in a Node.js environment. On client devices, you should instead initialize the SDK with an api key and auth domain","invalid-app-argument":"firebase.{$name}() takes either no argument or a Firebase App instance."});typeof firebase!=="undefined"&&(firebase=Ia()); }).call(this);
firebase.SDK_VERSION = "3.7.5";
'use strict';var n;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var p=ca(this);function r(a,b){if(b)a:{var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
r("Symbol",function(a){function b(g){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(g||"")+"_"+e++,g)}function c(g,f){this.g=g;ba(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=p[b[c]];typeof d==="function"&&typeof d.prototype[a]!="function"&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});function da(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
var ea=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;if(typeof Object.setPrototypeOf=="function")fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function la(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.K=b.prototype}function u(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function ma(a){return na(a,a)}
function na(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a}function oa(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}r("globalThis",function(a){return a||p});
r("Promise",function(a){function b(f){this.g=0;this.i=void 0;this.h=[];this.u=!1;var h=this.j();try{f(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.g=null}function d(f){return f instanceof b?f:new b(function(h){h(f)})}if(a)return a;c.prototype.h=function(f){if(this.g==null){this.g=[];var h=this;this.i(function(){h.l()})}this.g.push(f)};var e=p.setTimeout;c.prototype.i=function(f){e(f,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var h=0;h<f.length;++h){var k=
f[h];f[h]=null;try{k()}catch(l){this.j(l)}}}this.g=null};c.prototype.j=function(f){this.i(function(){throw f;})};b.prototype.j=function(){function f(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;return{resolve:f(this.C),reject:f(this.l)}};b.prototype.C=function(f){if(f===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.F(f);else{a:switch(typeof f){case "object":var h=f!=null;break a;case "function":h=!0;break a;default:h=!1}h?this.B(f):this.m(f)}};
b.prototype.B=function(f){var h=void 0;try{h=f.then}catch(k){this.l(k);return}typeof h=="function"?this.H(h,f):this.m(f)};b.prototype.l=function(f){this.o(2,f)};b.prototype.m=function(f){this.o(1,f)};b.prototype.o=function(f,h){if(this.g!=0)throw Error("Cannot settle("+f+", "+h+"): Promise already settled in state"+this.g);this.g=f;this.i=h;this.g===2&&this.G();this.v()};b.prototype.G=function(){var f=this;e(function(){if(f.A()){var h=p.console;typeof h!=="undefined"&&h.error(f.i)}},1)};b.prototype.A=
function(){if(this.u)return!1;var f=p.CustomEvent,h=p.Event,k=p.dispatchEvent;if(typeof k==="undefined")return!0;typeof f==="function"?f=new f("unhandledrejection",{cancelable:!0}):typeof h==="function"?f=new h("unhandledrejection",{cancelable:!0}):(f=p.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.i;return k(f)};b.prototype.v=function(){if(this.h!=null){for(var f=0;f<this.h.length;++f)g.h(this.h[f]);this.h=null}};var g=new c;b.prototype.F=
function(f){var h=this.j();f.N(h.resolve,h.reject)};b.prototype.H=function(f,h){var k=this.j();try{f.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(f,h){function k(q,t){return typeof q=="function"?function(z){try{l(q(z))}catch(D){m(D)}}:t}var l,m,x=new b(function(q,t){l=q;m=t});this.N(k(f,l),k(h,m));return x};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.N=function(f,h){function k(){switch(l.g){case 1:f(l.i);break;case 2:h(l.i);break;default:throw Error("Unexpected state: "+
l.g);}}var l=this;this.h==null?g.h(k):this.h.push(k);this.u=!0};b.resolve=d;b.reject=function(f){return new b(function(h,k){k(f)})};b.race=function(f){return new b(function(h,k){for(var l=u(f),m=l.next();!m.done;m=l.next())d(m.value).N(h,k)})};b.all=function(f){var h=u(f),k=h.next();return k.done?d([]):new b(function(l,m){function x(z){return function(D){q[z]=D;t--;t==0&&l(q)}}var q=[],t=0;do q.push(void 0),t++,d(k.value).N(x(q.length-1),m),k=h.next();while(!k.done)})};return b});
function v(a,b){return Object.prototype.hasOwnProperty.call(a,b)}r("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});
r("WeakMap",function(a){function b(k){this.g=(h+=Math.random()+1).toString();if(k){k=u(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return l==="object"&&k!==null||l==="function"}function e(k){if(!v(k,f)){var l=new c;ba(k,f,{value:l})}}function g(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(m.get(k)!=2||m.get(l)!=3)return!1;m.delete(k);m.set(l,4);return!m.has(k)&&m.get(l)==4}catch(x){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");g("seal");var h=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!v(k,f))throw Error("WeakMap key fail: "+k);k[f][this.g]=l;return this};b.prototype.get=function(k){return d(k)&&v(k,f)?k[f][this.g]:void 0};b.prototype.has=function(k){return d(k)&&v(k,
f)&&v(k[f],this.g)};b.prototype.delete=function(k){return d(k)&&v(k,f)&&v(k[f],this.g)?delete k[f][this.g]:!1};return b});
r("Map",function(a){function b(){var h={};return h.D=h.next=h.head=h}function c(h,k){var l=h[1];return da(function(){if(l){for(;l.head!=h[1];)l=l.D;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(h,k){var l=k&&typeof k;l=="object"||l=="function"?g.has(k)?l=g.get(k):(l=""+ ++f,g.set(k,l)):l="p_"+k;var m=h[0][l];if(m&&v(h[0],l))for(h=0;h<m.length;h++){var x=m[h];if(k!==k&&x.key!==x.key||k===x.key)return{id:l,list:m,index:h,entry:x}}return{id:l,
list:m,index:-1,entry:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=u(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),k=new a(u([[h,"s"]]));if(k.get(h)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=h||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(x){return!1}}())return a;var g=new WeakMap;e.prototype.set=function(h,k){h=h===0?0:h;var l=d(this,h);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=k:(l.entry={next:this[1],D:this[1].D,head:this[1],key:h,value:k},l.list.push(l.entry),this[1].D.next=l.entry,this[1].D=l.entry,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.entry&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],h.entry.D.next=h.entry.next,
h.entry.next.D=h.entry.D,h.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].D=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).entry};e.prototype.get=function(h){return(h=d(this,h).entry)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=
function(h,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,h.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var f=0;return e});function pa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}r("Array.prototype.entries",function(a){return a?a:function(){return pa(this,function(b,c){return[b,c]})}});
r("Array.prototype.keys",function(a){return a?a:function(){return pa(this,function(b){return b})}});r("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,g=0;g<e;g++){var f=d[g];if(b.call(c,f,g,d)){b=f;break a}}b=void 0}return b}});r("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)v(b,d)&&c.push([d,b[d]]);return c}});
r("Array.prototype.values",function(a){return a?a:function(){return pa(this,function(b,c){return c})}});r("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],g=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof g=="function"){b=g.call(b);for(var f=0;!(g=b.next()).done;)e.push(c.call(d,g.value,f++))}else for(g=b.length,f=0;f<g;f++)e.push(c.call(d,b[f],f));return e}});
r("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)v(b,d)&&c.push(b[d]);return c}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var qa=qa||{},w=this||self;function ra(a){var b=typeof a;b=b!="object"?b:a?Array.isArray(a)?"array":b:"null";return b=="array"||b=="object"&&typeof a.length=="number"}function y(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}function sa(a,b,c){return a.call.apply(a.bind,arguments)}
function ta(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function A(a,b,c){A=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?sa:ta;return A.apply(null,arguments)}
function B(a,b){function c(){}c.prototype=b.prototype;a.K=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.na=function(d,e,g){for(var f=Array(arguments.length-2),h=2;h<arguments.length;h++)f[h-2]=arguments[h];return b.prototype[e].apply(d,f)}};function C(a,b,c){this.code="auth/"+a;this.message=b||ua[a]||"";this.g=c||null}B(C,Error);C.prototype.toJSON=function(){var a={code:this.code,message:this.message};this.g&&(a.serverResponse=this.g);return a};
var ua={"api-key-service-blocked":"The request is denied because it violates [API key HTTP restrictions](https://cloud.google.com/docs/authentication/api-keys#adding_http_restrictions).","admin-restricted-operation":"This operation is restricted to administrators only.","argument-error":"","app-not-authorized":"This app, identified by the domain where it's hosted, is not authorized to use Firebase Authentication with the provided API key. Review your key configuration in the Google API console.","app-not-installed":"The requested mobile application corresponding to the identifier (Android package name or iOS bundle ID) provided is not installed on this device.",
"bad-request":"The requested action is invalid.","captcha-check-failed":"The reCAPTCHA response token provided is either invalid, expired, already used or the domain associated with it does not match the list of whitelisted domains.","code-expired":"The SMS code has expired. Please re-send the verification code to try again.","cordova-not-ready":"Cordova framework is not ready.","cors-unsupported":"This browser is not supported.","credential-already-in-use":"This credential is already associated with a different user account.",
"custom-token-mismatch":"The custom token corresponds to a different audience.","requires-recent-login":"This operation is sensitive and requires recent authentication. Log in again before retrying this request.","dynamic-link-not-activated":"Please activate Dynamic Links in the Firebase Console and agree to the terms and conditions.","email-change-needs-verification":"Multi-factor users must always have a verified email.","email-already-in-use":"The email address is already in use by another account.",
"expired-action-code":"The action code has expired. ","cancelled-popup-request":"This operation has been cancelled due to another conflicting popup being opened.","internal-error":"An internal error has occurred.","invalid-app-credential":"The phone verification request contains an invalid application verifier. The reCAPTCHA token response is either invalid or expired.","invalid-app-id":"The mobile app identifier is not registed for the current project.","invalid-user-token":"This user's credential isn't valid for this project. This can happen if the user's token has been tampered with, or if the user isn't for the project associated with this API key.",
"invalid-auth-event":"An internal error has occurred.","invalid-verification-code":"The SMS verification code used to create the phone auth credential is invalid. Please resend the verification code sms and be sure to use the verification code provided by the user.","invalid-continue-uri":"The continue URL provided in the request is invalid.","invalid-cordova-configuration":"The following Cordova plugins must be installed to enable OAuth sign-in: cordova-plugin-buildinfo, cordova-universal-links-plugin, cordova-plugin-browsertab, cordova-plugin-inappbrowser and cordova-plugin-customurlscheme.",
"invalid-custom-token":"The custom token format is incorrect. Please check the documentation.","invalid-dynamic-link-domain":"The provided dynamic link domain is not configured or authorized for the current project.","invalid-email":"The email address is badly formatted.","invalid-api-key":"Your API key is invalid, please check you have copied it correctly.","invalid-cert-hash":"The SHA-1 certificate hash provided is invalid.","invalid-credential":"The supplied auth credential is malformed or has expired.",
"invalid-message-payload":"The email template corresponding to this action contains invalid characters in its message. Please fix by going to the Auth email templates section in the Firebase Console.","invalid-multi-factor-session":"The request does not contain a valid proof of first factor successful sign-in.","invalid-oauth-provider":"EmailAuthProvider is not supported for this operation. This operation only supports OAuth providers.","invalid-oauth-client-id":"The OAuth client ID provided is either invalid or does not match the specified API key.",
"unauthorized-domain":"This domain is not authorized for OAuth operations for your Firebase project. Edit the list of authorized domains from the Firebase console.","invalid-action-code":"The action code is invalid. This can happen if the code is malformed, expired, or has already been used.","wrong-password":"The password is invalid or the user does not have a password.","invalid-persistence-type":"The specified persistence type is invalid. It can only be local, session or none.","invalid-phone-number":"The format of the phone number provided is incorrect. Please enter the phone number in a format that can be parsed into E.164 format. E.164 phone numbers are written in the format [+][country code][subscriber number including area code].",
"invalid-provider-id":"The specified provider ID is invalid.","invalid-recipient-email":"The email corresponding to this action failed to send as the provided recipient email address is invalid.","invalid-sender":"The email template corresponding to this action contains an invalid sender email or name. Please fix by going to the Auth email templates section in the Firebase Console.","invalid-verification-id":"The verification ID used to create the phone auth credential is invalid.","invalid-tenant-id":"The Auth instance's tenant ID is invalid.",
"multi-factor-info-not-found":"The user does not have a second factor matching the identifier provided.","multi-factor-auth-required":"Proof of ownership of a second factor is required to complete sign-in.","missing-android-pkg-name":"An Android Package Name must be provided if the Android App is required to be installed.","auth-domain-config-required":"Be sure to include authDomain when calling firebase.initializeApp(), by following the instructions in the Firebase console.","missing-app-credential":"The phone verification request is missing an application verifier assertion. A reCAPTCHA response token needs to be provided.",
"missing-verification-code":"The phone auth credential was created with an empty SMS verification code.","missing-continue-uri":"A continue URL must be provided in the request.","missing-iframe-start":"An internal error has occurred.","missing-ios-bundle-id":"An iOS Bundle ID must be provided if an App Store ID is provided.","missing-multi-factor-info":"No second factor identifier is provided.","missing-multi-factor-session":"The request is missing proof of first factor successful sign-in.","missing-or-invalid-nonce":"The request does not contain a valid nonce. This can occur if the SHA-256 hash of the provided raw nonce does not match the hashed nonce in the ID token payload.",
"missing-phone-number":"To send verification codes, provide a phone number for the recipient.","missing-verification-id":"The phone auth credential was created with an empty verification ID.","app-deleted":"This instance of FirebaseApp has been deleted.","account-exists-with-different-credential":"An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address.","network-request-failed":"A network error (such as timeout, interrupted connection or unreachable host) has occurred.",
"no-auth-event":"An internal error has occurred.","no-such-provider":"User was not linked to an account with the given provider.","null-user":"A null user object was provided as the argument for an operation which requires a non-null user object.","operation-not-allowed":"The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.","operation-not-supported-in-this-environment":'This operation is not supported in the environment this application is running on. "location.protocol" must be http, https or chrome-extension and web storage must be enabled.',
"password-does-not-meet-requirements":"The provided password does not meet the configured requirements.","popup-blocked":"Unable to establish a connection with the popup. It may have been blocked by the browser.","popup-closed-by-user":"The popup has been closed by the user before finalizing the operation.","provider-already-linked":"User can only be linked to one identity for the given provider.","quota-exceeded":"The project's quota for this operation has been exceeded.","redirect-cancelled-by-user":"The redirect operation has been cancelled by the user before finalizing.",
"redirect-operation-pending":"A redirect sign-in operation is already pending.","rejected-credential":"The request contains malformed or mismatching credentials.","second-factor-already-in-use":"The second factor is already enrolled on this account.","maximum-second-factor-count-exceeded":"The maximum allowed number of second factors on a user has been exceeded.","tenant-id-mismatch":"The provided tenant ID does not match the Auth instance's tenant ID",timeout:"The operation has timed out.","user-token-expired":"The user's credential is no longer valid. The user must sign in again.",
"too-many-requests":"We have blocked all requests from this device due to unusual activity. Try again later.","unauthorized-continue-uri":"The domain of the continue URL is not whitelisted.  Please whitelist the domain in the Firebase console.","unsupported-first-factor":"Enrolling a second factor or signing in with a multi-factor account requires sign-in with a supported first factor.","unsupported-persistence-type":"The current environment does not support the specified persistence type.","unsupported-tenant-operation":"This operation is not supported in a multi-tenant context.",
"unverified-email":"The operation requires a verified email.","user-cancelled":"The user did not grant your application the permissions it requested.","user-not-found":"There is no user record corresponding to this identifier. The user may have been deleted.","user-disabled":"The user account has been disabled by an administrator.","user-mismatch":"The supplied credentials do not correspond to the previously signed in user.","user-signed-out":"","weak-password":"The password must be 6 characters long or more.",
"web-storage-unsupported":"This browser is not supported or 3rd party cookies and data may be disabled."};function E(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,E);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)}B(E,Error);E.prototype.name="CustomError";var va;var wa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},xa=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},ya=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};function za(a){var b=a.length;if(b>0){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Aa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var Ba="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ca(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<Ba.length;g++)c=Ba[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function F(a,b){return a.indexOf(b)!=-1};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var Da=globalThis.trustedTypes,Ea;function Fa(){var a=null;if(!Da)return a;try{var b=function(c){return c};a=Da.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){}return a}function Ga(){Ea===void 0&&(Ea=Fa());return Ea};function Ha(a){this.g=a}Ha.prototype.toString=function(){return this.g+""};function Ia(a){var b=Ga();a=b?b.createScriptURL(a):a;return new Ha(a)}function Ja(a){if(a instanceof Ha)return a.g;throw Error("");};function G(a){this.g=a}G.prototype.toString=function(){return this.g};var Ka=new G("about:invalid#zClosurez");function La(a){this.ja=a}function H(a){return new La(function(b){return b.substr(0,a.length+1).toLowerCase()===a+":"})}var Ma=[H("data"),H("http"),H("https"),H("mailto"),H("ftp"),new La(function(a){return/^[^:]*([/?#]|$)/.test(a)})];function I(a){this.g=a}I.prototype.toString=function(){return this.g+""};function Na(a){var b=Ga();a=b?b.createHTML(a):a;return new I(a)}function Oa(a){if(a instanceof I)return a.g;throw Error("");};function Pa(a,b){b=b===void 0?document:b;var c,d;b=(d=(c=b).querySelector)==null?void 0:d.call(c,a+"[nonce]");return b==null?"":b.nonce||b.getAttribute("nonce")||""};function Qa(a,b){a.src=Ja(b);(b=Pa("script",a.ownerDocument))&&a.setAttribute("nonce",b)};function Ra(){this.g=Sa[0]}Ra.prototype.toString=function(){return this.g};var Ta,Ua;a:{for(var Va=["CLOSURE_FLAGS"],Wa=w,Xa=0;Xa<Va.length;Xa++)if(Wa=Wa[Va[Xa]],Wa==null){Ua=null;break a}Ua=Wa}var Ya=Ua&&Ua[610401301];Ta=Ya!=null?Ya:!1;function Za(){var a=w.navigator;return a&&(a=a.userAgent)?a:""}var $a,ab=w.navigator;$a=ab?ab.userAgentData||null:null;function J(a){return F(Za(),a)};var bb=Ta&&$a&&$a.brands.length>0?!1:J("Opera"),cb=Ta&&$a&&$a.brands.length>0?!1:J("Trident")||J("MSIE"),db=J("Edge"),eb=J("Gecko")&&!(F(Za().toLowerCase(),"webkit")&&!J("Edge"))&&!(J("Trident")||J("MSIE"))&&!J("Edge"),fb=F(Za().toLowerCase(),"webkit")&&!J("Edge");function gb(){var a=w.document;return a?a.documentMode:void 0}var hb;
a:{var ib="",jb=function(){var a=Za();if(eb)return/rv:([^\);]+)(\)|;)/.exec(a);if(db)return/Edge\/([\d\.]+)/.exec(a);if(cb)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(fb)return/WebKit\/(\S+)/.exec(a);if(bb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();jb&&(ib=jb?jb[1]:"");if(cb){var kb=gb();if(kb!=null&&kb>parseFloat(ib)){hb=String(kb);break a}}hb=ib}var lb=hb,mb;if(w.document&&cb){var nb=gb();mb=nb?nb:parseInt(lb,10)||void 0}else mb=void 0;var ob=mb;function pb(a){return a instanceof I?a:Na(String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;"))};function qb(a){var b=oa.apply(1,arguments);if(b.length===0)return Ia(a[0]);for(var c=a[0],d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return Ia(c)};function rb(a,b){Aa(b,function(c,d){d=="style"?a.style.cssText=c:d=="class"?a.className=c:d=="for"?a.htmlFor=c:sb.hasOwnProperty(d)?a.setAttribute(sb[d],c):d.lastIndexOf("aria-",0)==0||d.lastIndexOf("data-",0)==0?a.setAttribute(d,c):a[d]=c})}var sb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function tb(a,b,c){function d(h){h&&b.appendChild(typeof h==="string"?a.createTextNode(h):h)}for(var e=2;e<c.length;e++){var g=c[e];if(!ra(g)||y(g)&&g.nodeType>0)d(g);else{a:{if(g&&typeof g.length=="number"){if(y(g)){var f=typeof g.item=="function"||typeof g.item=="string";break a}if(typeof g==="function"){f=typeof g.item=="function";break a}}f=!1}xa(f?za(g):g,d)}}}function ub(a,b){b=String(b);a.contentType==="application/xhtml+xml"&&(b=b.toLowerCase());return a.createElement(b)}
function vb(a){this.g=a||w.document||document}function wb(a,b){a=a.g;return(b=b&&b!="*"?String(b).toUpperCase():"")?a.querySelectorAll(b):a.getElementsByTagName("*")}vb.prototype.h=function(a,b,c){var d=this.g,e=arguments,g=e[1],f=ub(d,String(e[0]));g&&(typeof g==="string"?f.className=g:Array.isArray(g)?f.className=g.join(" "):rb(f,g));e.length>2&&tb(d,f,e);return f};function xb(a,b){return ub(a.g,b)}vb.prototype.i=function(a,b){a.appendChild(b)};function K(){this.l=this.l;this.u=this.u}K.prototype.l=!1;K.prototype.isDisposed=function(){return this.l};K.prototype.dispose=function(){this.l||(this.l=!0,this.I())};K.prototype[Symbol.dispose]=function(){this.dispose()};K.prototype.I=function(){if(this.u)for(;this.u.length;)this.u.shift()()};function L(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1}L.prototype.h=function(){this.defaultPrevented=!0};var yb=function(){if(!w.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{var c=function(){};w.addEventListener("test",c,b);w.removeEventListener("test",c,b)}catch(d){}return a}();function M(a,b){L.call(this,a?a.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.i=null;a&&this.init(a,b)}B(M,L);
M.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;b=a.relatedTarget;b||(c=="mouseover"?b=a.fromElement:c=="mouseout"&&(b=a.toElement));this.relatedTarget=b;d?(this.clientX=d.clientX!==void 0?d.clientX:d.pageX,this.clientY=d.clientY!==void 0?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=a.clientX!==void 0?a.clientX:a.pageX,this.clientY=a.clientY!==
void 0?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=a.pointerType;this.state=a.state;this.i=a;a.defaultPrevented&&M.K.h.call(this)};M.prototype.h=function(){M.K.h.call(this);var a=this.i;a.preventDefault?a.preventDefault():a.returnValue=!1};var zb="closure_listenable_"+(Math.random()*1E6|0);var Ab=0;function Bb(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.P=e;this.key=++Ab;this.J=this.M=!1}function Cb(a){a.J=!0;a.listener=null;a.proxy=null;a.src=null;a.P=null};function Db(a){this.src=a;this.g={};this.h=0}Db.prototype.add=function(a,b,c,d,e){var g=a.toString();a=this.g[g];a||(a=this.g[g]=[],this.h++);var f=Eb(a,b,d,e);f>-1?(b=a[f],c||(b.M=!1)):(b=new Bb(b,this.src,g,!!d,e),b.M=c,a.push(b));return b};function Fb(a,b){var c=b.type;if(c in a.g){var d=a.g[c],e=wa(d,b),g;(g=e>=0)&&Array.prototype.splice.call(d,e,1);g&&(Cb(b),a.g[c].length==0&&(delete a.g[c],a.h--))}}
function Eb(a,b,c,d){for(var e=0;e<a.length;++e){var g=a[e];if(!g.J&&g.listener==b&&g.capture==!!c&&g.P==d)return e}return-1};var Gb="closure_lm_"+(Math.random()*1E6|0),Hb={},Ib=0;function Jb(a,b,c,d,e){if(d&&d.once)Kb(a,b,c,d,e);else if(Array.isArray(b))for(var g=0;g<b.length;g++)Jb(a,b[g],c,d,e);else c=Lb(c),a&&a[zb]?Mb(a,b,c,y(d)?!!d.capture:!!d,e):Nb(a,b,c,!1,d,e)}
function Nb(a,b,c,d,e,g){if(!b)throw Error("Invalid event type");var f=y(e)?!!e.capture:!!e,h=Ob(a);h||(a[Gb]=h=new Db(a));c=h.add(b,c,d,f,g);if(!c.proxy){d=Pb();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)yb||(e=f),e===void 0&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Qb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Ib++}}
function Pb(){function a(c){return b.call(a.src,a.listener,c)}var b=Rb;return a}function Kb(a,b,c,d,e){if(Array.isArray(b))for(var g=0;g<b.length;g++)Kb(a,b[g],c,d,e);else c=Lb(c),a&&a[zb]?Sb(a,b,c,y(d)?!!d.capture:!!d,e):Nb(a,b,c,!0,d,e)}
function Tb(a,b,c,d,e){if(Array.isArray(b))for(var g=0;g<b.length;g++)Tb(a,b[g],c,d,e);else(d=y(d)?!!d.capture:!!d,c=Lb(c),a&&a[zb])?(a=a.i,b=String(b).toString(),b in a.g&&(g=a.g[b],c=Eb(g,c,d,e),c>-1&&(Cb(g[c]),Array.prototype.splice.call(g,c,1),g.length==0&&(delete a.g[b],a.h--)))):a&&(a=Ob(a))&&(b=a.g[b.toString()],a=-1,b&&(a=Eb(b,c,d,e)),(c=a>-1?b[a]:null)&&Ub(c))}
function Ub(a){if(typeof a!=="number"&&a&&!a.J){var b=a.src;if(b&&b[zb])Fb(b.i,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Qb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Ib--;(c=Ob(b))?(Fb(c,a),c.h==0&&(c.src=null,b[Gb]=null)):Cb(a)}}}function Qb(a){return a in Hb?Hb[a]:Hb[a]="on"+a}function Rb(a,b){if(a.J)a=!0;else{b=new M(b,this);var c=a.listener,d=a.P||a.src;a.M&&Ub(a);a=c.call(d,b)}return a}
function Ob(a){a=a[Gb];return a instanceof Db?a:null}var Vb="__closure_events_fn_"+(Math.random()*1E9>>>0);function Lb(a){if(typeof a==="function")return a;a[Vb]||(a[Vb]=function(b){return a.handleEvent(b)});return a[Vb]};var N=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?function(a){return a&&AsyncContext.Snapshot.wrap(a)}:function(a){return a};function Wb(a,b){this.i=a;this.j=b;this.h=0;this.g=null}Wb.prototype.get=function(){if(this.h>0){this.h--;var a=this.g;this.g=a.next;a.next=null}else a=this.i();return a};function Xb(a,b){a.j(b);a.h<100&&(a.h++,b.next=a.g,a.g=b)};function Yb(a){w.setTimeout(function(){throw a;},0)};function Zb(){this.h=this.g=null}Zb.prototype.add=function(a,b){var c=$b.get();c.set(a,b);this.h?this.h.next=c:this.g=c;this.h=c};function ac(){var a=bc,b=null;a.g&&(b=a.g,a.g=a.g.next,a.g||(a.h=null),b.next=null);return b}var $b=new Wb(function(){return new cc},function(a){return a.reset()});function cc(){this.next=this.scope=this.g=null}cc.prototype.set=function(a,b){this.g=a;this.scope=b;this.next=null};cc.prototype.reset=function(){this.next=this.scope=this.g=null};var dc,ec=!1,bc=new Zb;function fc(a,b){dc||hc();ec||(dc(),ec=!0);bc.add(a,b)}function hc(){var a=Promise.resolve(void 0);dc=function(){a.then(ic)}}function ic(){for(var a;a=ac();){try{a.g.call(a.scope)}catch(b){Yb(b)}Xb($b,a)}ec=!1};function jc(){};function kc(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};function O(a){this.g=0;this.u=void 0;this.j=this.h=this.i=null;this.l=this.m=!1;if(a!=jc)try{var b=this;a.call(void 0,function(c){P(b,2,c)},function(c){P(b,3,c)})}catch(c){P(this,3,c)}}function lc(){this.next=this.i=this.h=this.j=this.g=null;this.l=!1}lc.prototype.reset=function(){this.i=this.h=this.j=this.g=null;this.l=!1};var mc=new Wb(function(){return new lc},function(a){a.reset()});function nc(a,b,c){var d=mc.get();d.j=a;d.h=b;d.i=c;return d}
function Q(a){if(a instanceof O)return a;var b=new O(jc);P(b,2,a);return b}function oc(){var a=new C("internal-error");return new O(function(b,c){c(a)})}O.prototype.then=function(a,b,c){return pc(this,N(typeof a==="function"?a:null),N(typeof b==="function"?b:null),c)};O.prototype.$goog_Thenable=!0;function qc(a,b){return pc(a,null,N(b))}O.prototype.cancel=function(a){if(this.g==0){var b=new rc(a);fc(function(){sc(this,b)},this)}};
function sc(a,b){if(a.g==0)if(a.i){var c=a.i;if(c.h){for(var d=0,e=null,g=null,f=c.h;f&&(f.l||(d++,f.g==a&&(e=f),!(e&&d>1)));f=f.next)e||(g=f);e&&(c.g==0&&d==1?sc(c,b):(g?(d=g,d.next==c.j&&(c.j=d),d.next=d.next.next):tc(c),uc(c,e,3,b)))}a.i=null}else P(a,3,b)}function vc(a,b){a.h||a.g!=2&&a.g!=3||wc(a);a.j?a.j.next=b:a.h=b;a.j=b}
function pc(a,b,c,d){var e=nc(null,null,null);e.g=new O(function(g,f){e.j=b?function(h){try{var k=b.call(d,h);g(k)}catch(l){f(l)}}:g;e.h=c?function(h){try{var k=c.call(d,h);k===void 0&&h instanceof rc?f(h):g(k)}catch(l){f(l)}}:f});e.g.i=a;vc(a,e);return e.g}O.prototype.v=function(a){this.g=0;P(this,2,a)};O.prototype.A=function(a){this.g=0;P(this,3,a)};
function P(a,b,c){if(a.g==0){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.g=1;a:{var d=c,e=a.v,g=a.A;if(d instanceof O){vc(d,nc(e||jc,g||null,a));var f=!0}else if(kc(d))d.then(e,g,a),f=!0;else{if(y(d))try{var h=d.then;if(typeof h==="function"){xc(d,h,e,g,a);f=!0;break a}}catch(k){g.call(a,k);f=!0;break a}f=!1}}f||(a.u=c,a.g=b,a.i=null,wc(a),b!=3||c instanceof rc||yc(a,c))}}
function xc(a,b,c,d,e){function g(k){h||(h=!0,d.call(e,k))}function f(k){h||(h=!0,c.call(e,k))}var h=!1;try{b.call(a,f,g)}catch(k){g(k)}}function wc(a){a.m||(a.m=!0,fc(a.o,a))}function tc(a){var b=null;a.h&&(b=a.h,a.h=b.next,b.next=null);a.h||(a.j=null);return b}O.prototype.o=function(){for(var a;a=tc(this);)uc(this,a,this.g,this.u);this.m=!1};
function uc(a,b,c,d){if(c==3&&b.h&&!b.l)for(;a&&a.l;a=a.i)a.l=!1;if(b.g)b.g.i=null,zc(b,c,d);else try{b.l?b.j.call(b.i):zc(b,c,d)}catch(e){Ac.call(null,e)}Xb(mc,b)}function zc(a,b,c){b==2?a.j.call(a.i,c):a.h&&a.h.call(a.i,c)}function yc(a,b){a.l=!0;fc(function(){a.l&&Ac.call(null,b)})}var Ac=Yb;function rc(a){E.call(this,a)}B(rc,E);rc.prototype.name="cancel";function R(){K.call(this);this.i=new Db(this);this.Z=this;this.G=null}B(R,K);R.prototype[zb]=!0;R.prototype.addEventListener=function(a,b,c,d){Jb(this,a,b,c,d)};R.prototype.removeEventListener=function(a,b,c,d){Tb(this,a,b,c,d)};
R.prototype.dispatchEvent=function(a){var b,c=this.G;if(c)for(b=[];c;c=c.G)b.push(c);c=this.Z;var d=a.type||a;if(typeof a==="string")a=new L(a,c);else if(a instanceof L)a.target=a.target||c;else{var e=a;a=new L(d,c);Ca(a,e)}e=!0;var g;if(b)for(g=b.length-1;g>=0;g--){var f=a.g=b[g];e=Bc(f,d,!0,a)&&e}f=a.g=c;e=Bc(f,d,!0,a)&&e;e=Bc(f,d,!1,a)&&e;if(b)for(g=0;g<b.length;g++)f=a.g=b[g],e=Bc(f,d,!1,a)&&e;return e};
R.prototype.I=function(){R.K.I.call(this);if(this.i){var a=this.i,b=0,c;for(c in a.g){for(var d=a.g[c],e=0;e<d.length;e++)++b,Cb(d[e]);delete a.g[c];a.h--}}this.G=null};function Mb(a,b,c,d,e){a.i.add(String(b),c,!1,d,e)}function Sb(a,b,c,d,e){a.i.add(String(b),c,!0,d,e)}
function Bc(a,b,c,d){b=a.i.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,g=0;g<b.length;++g){var f=b[g];if(f&&!f.J&&f.capture==c){var h=f.listener,k=f.P||f.src;f.M&&Fb(a.i,f);e=h.call(k,d)!==!1&&e}}return e&&!d.defaultPrevented};var Cc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Dc(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(d>=0){var g=a[c].substring(0,d);e=a[c].substring(d+1)}else g=a[c];b(g,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function S(a){this.g=this.u=this.i="";this.o=null;this.m=this.j="";this.l=!1;var b;a instanceof S?(this.l=a.l,Ec(this,a.i),this.u=a.u,this.g=a.g,Fc(this,a.o),this.j=a.j,Gc(this,Hc(a.h)),this.m=a.m):a&&(b=String(a).match(Cc))?(this.l=!1,Ec(this,b[1]||"",!0),this.u=Ic(b[2]||""),this.g=Ic(b[3]||"",!0),Fc(this,b[4]),this.j=Ic(b[5]||"",!0),Gc(this,b[6]||"",!0),this.m=Ic(b[7]||"")):(this.l=!1,this.h=new Jc(null,this.l))}
S.prototype.toString=function(){var a=[],b=this.i;b&&a.push(Kc(b,Lc,!0),":");var c=this.g;if(c||b=="file")a.push("//"),(b=this.u)&&a.push(Kc(b,Lc,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.o,c!=null&&a.push(":",String(c));if(c=this.j)this.g&&c.charAt(0)!="/"&&a.push("/"),a.push(Kc(c,c.charAt(0)=="/"?Mc:Nc,!0));(c=this.h.toString())&&a.push("?",c);(c=this.m)&&a.push("#",Kc(c,Oc));return a.join("")};
S.prototype.resolve=function(a){var b=new S(this),c=!!a.i;c?Ec(b,a.i):c=!!a.u;c?b.u=a.u:c=!!a.g;c?b.g=a.g:c=a.o!=null;var d=a.j;if(c)Fc(b,a.o);else if(c=!!a.j){if(d.charAt(0)!="/")if(this.g&&!this.j)d="/"+d;else{var e=b.j.lastIndexOf("/");e!=-1&&(d=b.j.slice(0,e+1)+d)}e=d;if(e==".."||e==".")d="";else if(F(e,"./")||F(e,"/.")){d=e.lastIndexOf("/",0)==0;e=e.split("/");for(var g=[],f=0;f<e.length;){var h=e[f++];h=="."?d&&f==e.length&&g.push(""):h==".."?((g.length>1||g.length==1&&g[0]!="")&&g.pop(),d&&
f==e.length&&g.push("")):(g.push(h),d=!0)}d=g.join("/")}else d=e}c?b.j=d:c=a.h.toString()!=="";c?Gc(b,Hc(a.h)):c=!!a.m;c&&(b.m=a.m);return b};function Ec(a,b,c){a.i=c?Ic(b,!0):b;a.i&&(a.i=a.i.replace(/:$/,""))}function Fc(a,b){if(b){b=Number(b);if(isNaN(b)||b<0)throw Error("Bad port number "+b);a.o=b}else a.o=null}function Gc(a,b,c){b instanceof Jc?(a.h=b,Pc(a.h,a.l)):(c||(b=Kc(b,Qc)),a.h=new Jc(b,a.l))}function Rc(a,b){return a.h.get(b)}function T(a){return a instanceof S?new S(a):new S(a)}
function Ic(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function Kc(a,b,c){return typeof a==="string"?(a=encodeURI(a).replace(b,Sc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function Sc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Lc=/[#\/\?@]/g,Nc=/[#\?:]/g,Mc=/[#\?]/g,Qc=/[#\?@]/g,Oc=/#/g;function Jc(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b}
function U(a){a.g||(a.g=new Map,a.h=0,a.i&&Dc(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}n=Jc.prototype;n.add=function(a,b){U(this);this.i=null;a=V(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};function Tc(a,b){U(a);b=V(a,b);a.g.has(b)&&(a.i=null,a.h-=a.g.get(b).length,a.g.delete(b))}function Uc(a,b){U(a);b=V(a,b);return a.g.has(b)}
n.forEach=function(a,b){U(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};function Vc(a,b){U(a);var c=[];if(typeof b==="string")Uc(a,b)&&(c=c.concat(a.g.get(V(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c}n.set=function(a,b){U(this);this.i=null;a=V(this,a);Uc(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};
n.get=function(a,b){if(!a)return b;a=Vc(this,a);return a.length>0?String(a[0]):b};n.toString=function(){if(this.i)return this.i;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=Vc(this,d);for(var g=0;g<d.length;g++){var f=e;d[g]!==""&&(f+="="+encodeURIComponent(String(d[g])));a.push(f)}}return this.i=a.join("&")};function Hc(a){var b=new Jc;b.i=a.i;a.g&&(b.g=new Map(a.g),b.h=a.h);return b}
function V(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b}function Pc(a,b){b&&!a.j&&(U(a),a.i=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Tc(this,d),Tc(this,e),c.length>0&&(this.i=null,this.g.set(V(this,e),za(c)),this.h+=c.length))},a));a.j=b};function Wc(){var a=Xc();a=Yc(a)!="Chrome"?null:(a=a.match(/\sChrome\/(\d+)/i))&&a.length==2?parseInt(a[1],10):null;return a&&a<30?!1:!cb||!ob||ob>9}function Zc(a,b){var c=T(b);b=c.i;c=c.g;for(var d=0;d<a.length;d++){var e=a[d];e.indexOf("chrome-extension://")==0?e=T(e).g==c&&b=="chrome-extension":b!="http"&&b!="https"?e=!1:$c.test(e)?e=c==e:(e=e.split(".").join("\\."),e=(new RegExp("^(.+\\."+e+"|"+e+")$","i")).test(c));if(e)return!0}return!1}var $c=/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/;
function ad(){var a=null;return qc(new O(function(b){w.document.readyState=="complete"?b():(a=function(){b()},Kb(window,"load",a))}),function(b){Tb(window,"load",a);throw b;})}function bd(){return typeof w.WorkerGlobalScope!=="undefined"&&typeof w.importScripts==="function"}function cd(){return firebase.INTERNAL.hasOwnProperty("reactNative")?"ReactNative":firebase.INTERNAL.hasOwnProperty("node")?"Node":bd()?"Worker":"Browser"}
function Yc(a){var b=a.toLowerCase();if(F(b,"opera/")||F(b,"opr/")||F(b,"opios/"))return"Opera";if(F(b,"iemobile"))return"IEMobile";if(F(b,"msie")||F(b,"trident/"))return"IE";if(F(b,"edge/"))return"Edge";if(F(b,"firefox/"))return"Firefox";if(F(b,"silk/"))return"Silk";if(F(b,"blackberry"))return"Blackberry";if(F(b,"webos"))return"Webos";if(!F(b,"safari/")||F(b,"chrome/")||F(b,"crios/")||F(b,"android"))if(!F(b,"chrome/")&&!F(b,"crios/")||F(b,"edge/")){if(F(b,"android"))return"Android";if((a=a.match(RegExp("([a-zA-Z\\d\\.]+)/[a-zA-Z\\d\\.]*$")))&&
a.length==2)return a[1]}else return"Chrome";else return"Safari";return"Other"}function Xc(){return w.navigator&&w.navigator.userAgent||""}function dd(){return w.location&&w.location.protocol||null}function ed(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&a[c]!==null&&a[c]!==void 0&&(b[c]=a[c]);return b}
function fd(){var a=Xc(),b=cd();a=(a||Xc()).toLowerCase();this.g=(a.match(/android/)||a.match(/webos/)||a.match(/iphone|ipad|ipod/)||a.match(/blackberry/)||a.match(/windows phone/)||a.match(/iemobile/)?!0:!1)||b==="ReactNative"}fd.prototype.get=function(){var a=w.navigator;return!a||typeof a.onLine!=="boolean"||dd()!=="http:"&&dd()!=="https:"&&dd()!=="chrome-extension:"&&typeof a.connection==="undefined"||a.onLine?this.g?6E4:3E4:5E3};
function gd(a){typeof console!=="undefined"&&typeof console.error==="function"&&console.error(a)};var hd;try{var id={};Object.defineProperty(id,"abcd",{configurable:!0,enumerable:!0,value:1});Object.defineProperty(id,"abcd",{configurable:!0,enumerable:!0,value:2});hd=id.abcd==2}catch(a){hd=!1}function W(a,b,c){hd?Object.defineProperty(a,b,{configurable:!0,enumerable:!0,value:c}):a[b]=c}function X(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&W(a,c,b[c])}
function jd(a,b){if(!b||!b.length)return!0;if(!a)return!1;for(var c=0;c<b.length;c++){var d=a[b[c]];if(d===void 0||d===null||d==="")return!1}return!0};function kd(){};var ld;function md(){}B(md,kd);md.prototype.g=function(){return new XMLHttpRequest};ld=new md;function nd(){}B(nd,kd);nd.prototype.g=function(){var a=new XMLHttpRequest;if("withCredentials"in a)return a;if(typeof XDomainRequest!="undefined")return new od;throw Error("Unsupported browser");};function od(){this.g=new XDomainRequest;this.readyState=0;this.onreadystatechange=null;this.responseType=this.responseText=this.response="";this.status=-1;this.statusText="";this.g.onload=A(this.ca,this);this.g.onerror=A(this.U,this);this.g.onprogress=A(this.da,this);this.g.ontimeout=A(this.ha,this)}
n=od.prototype;n.open=function(a,b,c){if(c!=null&&!c)throw Error("Only async requests are supported.");this.g.open(a,b)};n.send=function(a){if(a)if(typeof a=="string")this.g.send(a);else throw Error("Only string data is supported");else this.g.send()};n.abort=function(){this.g.abort()};n.setRequestHeader=function(){};n.getResponseHeader=function(a){return a.toLowerCase()=="content-type"?this.g.contentType:""};
n.ca=function(){this.status=200;this.response=this.responseText=this.g.responseText;pd(this,4)};n.U=function(){this.status=500;this.response=this.responseText="";pd(this,4)};n.ha=function(){this.U()};n.da=function(){this.status=200;pd(this,1)};function pd(a,b){a.readyState=b;if(a.onreadystatechange)a.onreadystatechange()}n.getAllResponseHeaders=function(){return"content-type: "+this.g.contentType};function qd(a){R.call(this);this.headers=new Map;this.L=a||null;this.h=!1;this.g=null;this.C="";this.j=this.B=this.m=this.A=!1;this.v=0;this.o=null;this.F="";this.H=!1}B(qd,R);var rd=/^https?$/i,td=["POST","PUT"];
function ud(a,b,c,d,e){if(a.g)throw Error("[goog.net.XhrIo] Object is active with another request="+a.C+"; newUri="+b);c=c?c.toUpperCase():"GET";a.C=b;a.A=!1;a.h=!0;a.g=a.L?a.L.g():ld.g();a.g.onreadystatechange=N(A(a.V,a));try{a.B=!0,a.g.open(c,String(b),!0),a.B=!1}catch(h){vd(a);return}b=d||"";d=new Map(a.headers);if(e)if(Object.getPrototypeOf(e)===Object.prototype)for(var g in e)d.set(g,e[g]);else if(typeof e.keys==="function"&&typeof e.get==="function"){g=u(e.keys());for(var f=g.next();!f.done;f=
g.next())f=f.value,d.set(f,e.get(f))}else throw Error("Unknown input type for opt_headers: "+String(e));e=Array.from(d.keys()).find(function(h){return"content-type"==h.toLowerCase()});g=w.FormData&&b instanceof w.FormData;!(wa(td,c)>=0)||e||g||d.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");c=u(d);for(e=c.next();!e.done;e=c.next())d=u(e.value),e=d.next().value,d=d.next().value,a.g.setRequestHeader(e,d);a.F&&(a.g.responseType=a.F);"withCredentials"in a.g&&a.g.withCredentials!==
a.H&&(a.g.withCredentials=a.H);try{wd(a),a.v>0&&(a.o=setTimeout(a.R.bind(a),a.v)),a.m=!0,a.g.send(b),a.m=!1}catch(h){vd(a)}}n=qd.prototype;n.R=function(){typeof qa!="undefined"&&this.g&&(this.dispatchEvent("timeout"),this.abort(8))};function vd(a){a.h=!1;a.g&&(a.j=!0,a.g.abort(),a.j=!1);xd(a);yd(a)}function xd(a){a.A||(a.A=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))}
n.abort=function(){this.g&&this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1,this.dispatchEvent("complete"),this.dispatchEvent("abort"),yd(this))};n.I=function(){this.g&&(this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1),yd(this,!0));qd.K.I.call(this)};n.V=function(){this.isDisposed()||(this.B||this.m||this.j?zd(this):this.ka())};n.ka=function(){zd(this)};
function zd(a){if(a.h&&typeof qa!="undefined")if(a.m&&(a.g?a.g.readyState:0)==4)setTimeout(a.V.bind(a),0);else if(a.dispatchEvent("readystatechange"),(a.g?a.g.readyState:0)==4){a.h=!1;try{var b=Ad(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=b===0){var g=String(a.C).match(Cc)[1]||null;!g&&w.self&&w.self.location&&(g=w.self.location.protocol.slice(0,-1));e=!rd.test(g?g.toLowerCase():"")}d=e}d?(a.dispatchEvent("complete"),
a.dispatchEvent("success")):xd(a)}finally{yd(a)}}}function yd(a,b){if(a.g){wd(a);var c=a.g;a.g=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=null}catch(d){}}}function wd(a){a.o&&(clearTimeout(a.o),a.o=null)}n.isActive=function(){return!!this.g};function Ad(a){try{return(a.g?a.g.readyState:0)>2?a.g.status:-1}catch(b){return-1}}function Bd(a){try{return a.g?a.g.responseText:""}catch(b){return""}}
n.getResponse=function(){try{if(!this.g)return null;if("response"in this.g)return this.g.response;switch(this.F){case "":case "text":return this.g.responseText;case "arraybuffer":if("mozResponseArrayBuffer"in this.g)return this.g.mozResponseArrayBuffer}return null}catch(a){return null}};function Cd(){this.g=new nd}
function Dd(){var a=new qd((new Cd).g),b={"Content-type":"application/json"};return new O(function(c,d){try{a.v=1E4;var e=setTimeout(function(){a.dispatchEvent("timeout")},1E4);Mb(a,"complete",function(){e&&clearTimeout(e);var g=null,f=Bd(a);if(Ad(a)===200)try{g=JSON.parse(f)||null,c(g||null)}catch(h){d(Error(f))}else Ad(a)===404?d(Error("resource-not-found")):d(Error(f))});Sb(a,"ready",function(){e&&clearTimeout(e);a.dispose()});Sb(a,"timeout",function(){e&&clearTimeout(e);a.dispose();d(Error("Request timed out"))});
ud(a,"/__/firebase/init.json","GET",null,b)}catch(g){d(g)}})};var Ed="oauth_consumer_key oauth_nonce oauth_signature oauth_signature_method oauth_timestamp oauth_token oauth_version".split(" "),Fd=["client_id","response_type","scope","redirect_uri","state"];function Gd(a){X(this,{providerId:a,isOAuthProvider:!0})}function Y(a){Gd.call(this,a,Fd);this.g=[]}B(Y,Gd);function Hd(){Y.call(this,"facebook.com")}B(Hd,Y);W(Hd,"PROVIDER_ID","facebook.com");W(Hd,"FACEBOOK_SIGN_IN_METHOD","facebook.com");function Id(){Y.call(this,"github.com")}B(Id,Y);W(Id,"PROVIDER_ID","github.com");W(Id,"GITHUB_SIGN_IN_METHOD","github.com");function Jd(){Y.call(this,"google.com");wa(this.g,"profile")>=0||this.g.push("profile")}B(Jd,Y);W(Jd,"PROVIDER_ID","google.com");
W(Jd,"GOOGLE_SIGN_IN_METHOD","google.com");function Kd(){Gd.call(this,"twitter.com",Ed)}B(Kd,Gd);W(Kd,"PROVIDER_ID","twitter.com");W(Kd,"TWITTER_SIGN_IN_METHOD","twitter.com");function Ld(){X(this,{providerId:"password",isOAuthProvider:!1})}X(Ld,{PROVIDER_ID:"password"});X(Ld,{EMAIL_LINK_SIGN_IN_METHOD:"emailLink"});X(Ld,{EMAIL_PASSWORD_SIGN_IN_METHOD:"password"});
function Md(a){try{a||firebase.auth()}catch(b){throw new C("argument-error","Either an instance of firebase.auth.Auth must be passed as an argument to the firebase.auth.PhoneAuthProvider constructor, or the default firebase App instance must be initialized via firebase.initializeApp().");}X(this,{providerId:"phone",isOAuthProvider:!1})}X(Md,{PROVIDER_ID:"phone"});X(Md,{PHONE_SIGN_IN_METHOD:"phone"});var Nd={};function Od(){throw Error("Do not instantiate directly");}Od.prototype.T=null;Od.prototype.toString=function(){return this.content};Od.prototype.Y=function(){if(this.g!==Nd)throw Error("Sanitized content was not of kind HTML.");return Na(this.toString())};function Pd(){Od.call(this)}B(Pd,Od);Pd.prototype.g=Nd;function Qd(a){if(a!=null)switch(a.T){case 1:return 1;case -1:return-1;case 0:return 0}return null}var Rd=function(a){function b(c){this.content=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));d!==void 0&&(c.T=d);return c}}(Pd);function Sd(){return Td(function(){return""}).replace(Ud,"&lt;")}var Vd=RegExp.prototype.hasOwnProperty("sticky"),Wd=new RegExp((Vd?"":"^")+"(?:!|/?([a-zA-Z][a-zA-Z0-9:-]*))",Vd?"gy":"g");
function Td(a){for(var b=String("firebase-container".content),c=[],d=b.length,e=0,g=[],f,h,k=0;k<d;){switch(e){case 0:var l=b.indexOf("<",k);if(l<0){if(c.length===0)return b;c.push(b.substring(k));k=d}else c.push(b.substring(k,l)),h=l,k=l+1,Vd?(Wd.lastIndex=k,l=Wd.exec(b)):(Wd.lastIndex=0,l=Wd.exec(b.substring(k))),l?(g=["<",l[0]],f=l[1],e=1,k+=l[0].length):c.push("<");break;case 1:l=b.charAt(k++);switch(l){case "'":case '"':var m=b.indexOf(l,k);m<0?k=d:(g.push(l,b.substring(k,m+1)),k=m+1);break;
case ">":g.push(l);c.push(a(g.join(""),f));e=0;g=[];h=f=null;break;default:g.push(l)}break;default:throw Error();}e===1&&k>=d&&(k=h+1,c.push("<"),e=0,g=[],h=f=null)}return c.join("")}var Xd={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\v":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function Yd(a){return Xd[a]}
var Zd=/[\x00\x22\x26\x27\x3c\x3e]/g,$d=/[\x00\x22\x27\x3c\x3e]/g,Ud=/</g;/*
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var ae={};function be(a){a=a.errorMessage;if("firebase-container".g===Nd){var b=Sd();b=String(b).replace($d,Yd)}else b="firebase-container".replace(Zd,Yd);return Rd('<div id="error-screen" class="'+b+'">'+(a!=null&&a.g===Nd?a:a instanceof I?Rd(Oa(a).toString()):Rd(String(String(a)).replace(Zd,Yd),Qd(a)))+"</div>")};function ce(a,b){this.i=a;this.h=b;this.g=null}ce.prototype.render=function(a){var b=(0,this.i)(this.h||ae,void 0);var c=va||(va=new vb);if(b&&b.h)c=b.h();else{c=xb(c,"DIV");b:if(y(b)){if(b.Y&&(b=b.Y(),b instanceof I))break b;b=pb("zSoyz")}else b=pb(String(b));c.innerHTML=Oa(b)}c.childNodes.length==1&&(b=c.firstChild,b.nodeType==1&&(c=b));this.g=c;a.appendChild(this.g)};ce.prototype.dispose=function(){if(this.g){var a=this.g;a&&a.parentNode&&a.parentNode.removeChild(a);this.g=null}};
function de(a){ce.call(this,be,{errorMessage:a})}la(de,ce);function ee(a){this.i=a.ma||null;this.h=a.ua||!1}B(ee,kd);ee.prototype.g=function(){return new fe(this.i,this.h)};function fe(a,b){R.call(this);this.L=a;this.v=b;this.o=void 0;this.status=this.readyState=0;this.responseType=this.responseText=this.response=this.statusText="";this.onreadystatechange=null;this.B=new Headers;this.h=null;this.F="GET";this.H="";this.g=!1;this.C=this.j=this.m=null;this.A=new AbortController}B(fe,R);n=fe.prototype;
n.open=function(a,b){if(this.readyState!=0)throw this.abort(),Error("Error reopening a connection");this.F=a;this.H=b;this.readyState=1;ge(this)};n.send=function(a){if(this.readyState!=1)throw this.abort(),Error("need to call open() first. ");if(this.A.signal.aborted)throw this.abort(),Error("Request was aborted.");this.g=!0;var b={headers:this.B,method:this.F,credentials:this.o,cache:void 0,signal:this.A.signal};a&&(b.body=a);(this.L||w).fetch(new Request(this.H,b)).then(this.ga.bind(this),this.O.bind(this))};
n.abort=function(){this.response=this.responseText="";this.B=new Headers;this.status=0;this.A.abort();this.j&&this.j.cancel("Request was aborted.").catch(function(){});this.readyState>=1&&this.g&&this.readyState!=4&&(this.g=!1,he(this));this.readyState=0};
n.ga=function(a){if(this.g&&(this.m=a,this.h||(this.status=this.m.status,this.statusText=this.m.statusText,this.h=a.headers,this.readyState=2,ge(this)),this.g&&(this.readyState=3,ge(this),this.g)))if(this.responseType==="arraybuffer")a.arrayBuffer().then(this.ea.bind(this),this.O.bind(this));else if(typeof w.ReadableStream!=="undefined"&&"body"in a){this.j=a.body.getReader();if(this.v){if(this.responseType)throw Error('responseType must be empty for "streamBinaryChunks" mode responses.');this.response=
[]}else this.response=this.responseText="",this.C=new TextDecoder;ie(this)}else a.text().then(this.fa.bind(this),this.O.bind(this))};function ie(a){a.j.read().then(a.ba.bind(a)).catch(a.O.bind(a))}n.ba=function(a){if(this.g){if(this.v&&a.value)this.response.push(a.value);else if(!this.v){var b=a.value?a.value:new Uint8Array(0);if(b=this.C.decode(b,{stream:!a.done}))this.response=this.responseText+=b}a.done?he(this):ge(this);this.readyState==3&&ie(this)}};
n.fa=function(a){this.g&&(this.response=this.responseText=a,he(this))};n.ea=function(a){this.g&&(this.response=a,he(this))};n.O=function(){this.g&&he(this)};function he(a){a.readyState=4;a.m=null;a.j=null;a.C=null;ge(a)}n.setRequestHeader=function(a,b){this.B.append(a,b)};n.getResponseHeader=function(a){return this.h?this.h.get(a.toLowerCase())||"":""};
n.getAllResponseHeaders=function(){if(!this.h)return"";for(var a=[],b=this.h.entries(),c=b.next();!c.done;)c=c.value,a.push(c[0]+": "+c[1]),c=b.next();return a.join("\r\n")};function ge(a){a.onreadystatechange&&a.onreadystatechange.call(a)}Object.defineProperty(fe.prototype,"withCredentials",{get:function(){return this.o==="include"},set:function(a){this.o=a?"include":"same-origin"}});/*

 Copyright 2005, 2007 Bob Ippolito. All Rights Reserved.
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: MIT
*/
function Z(a){var b=je;this.l=[];this.C=b;this.B=a||null;this.j=this.i=!1;this.h=void 0;this.v=this.G=this.u=!1;this.m=0;this.g=null;this.o=0}Z.prototype.cancel=function(a){if(this.i)this.h instanceof Z&&this.h.cancel();else{if(this.g){var b=this.g;delete this.g;a?b.cancel(a):(b.o--,b.o<=0&&b.cancel())}this.C?this.C.call(this.B,this):this.v=!0;this.i||(a=new ke(this),le(this),me(this,!1,a))}};Z.prototype.A=function(a,b){this.u=!1;me(this,a,b)};function me(a,b,c){a.i=!0;a.h=c;a.j=!b;ne(a)}
function le(a){if(a.i){if(!a.v)throw new oe(a);a.v=!1}}function pe(a,b){qe(a,null,b)}function qe(a,b,c,d){var e=a.i;e||(b===c?b=c=N(b):(b=N(b),c=N(c)));a.l.push([b,c,d]);e&&ne(a)}Z.prototype.then=function(a,b,c){var d,e,g=new O(function(f,h){e=f;d=h});qe(this,e,function(f){f instanceof ke?g.cancel():d(f);return re},this);return g.then(a,b,c)};Z.prototype.$goog_Thenable=!0;function se(a){return ya(a.l,function(b){return typeof b[1]==="function"})}var re={};
function ne(a){if(a.m&&a.i&&se(a)){var b=a.m,c=te[b];c&&(w.clearTimeout(c.g),delete te[b]);a.m=0}a.g&&(a.g.o--,delete a.g);b=a.h;for(var d=c=!1;a.l.length&&!a.u;){var e=a.l.shift(),g=e[0],f=e[1];e=e[2];if(g=a.j?f:g)try{var h=g.call(e||a.B,b);h===re&&(h=void 0);h!==void 0&&(a.j=a.j&&(h==b||h instanceof Error),a.h=b=h);if(kc(b)||typeof w.Promise==="function"&&b instanceof w.Promise)d=!0,a.u=!0}catch(k){b=k,a.j=!0,se(a)||(c=!0)}}a.h=b;d&&(h=A(a.A,a,!0),d=A(a.A,a,!1),b instanceof Z?(qe(b,h,d),b.G=!0):
b.then(h,d));c&&(b=new ue(b),te[b.g]=b,a.m=b.g)}function oe(){E.call(this)}B(oe,E);oe.prototype.message="Deferred has already fired";oe.prototype.name="AlreadyCalledError";function ke(){E.call(this)}B(ke,E);ke.prototype.message="Deferred was canceled";ke.prototype.name="CanceledError";function ue(a){this.g=w.setTimeout(A(this.i,this),0);this.h=a}ue.prototype.i=function(){delete te[this.g];throw this.h;};var te={};function ve(a){var b={},c=b.document||document,d=Ja(a).toString(),e=xb(new vb(c),"SCRIPT"),g={X:e,R:void 0},f=new Z(g),h=null,k=b.timeout!=null?b.timeout:5E3;k>0&&(h=window.setTimeout(function(){we(e,!0);var l=new xe(1,"Timeout reached for loading script "+d);le(f);me(f,!1,l)},k),g.R=h);e.onload=e.onreadystatechange=function(){e.readyState&&e.readyState!="loaded"&&e.readyState!="complete"||(we(e,b.oa||!1,h),le(f),me(f,!0,null))};e.onerror=function(){we(e,!0,h);var l=new xe(0,"Error while loading script "+
d);le(f);me(f,!1,l)};g=b.attributes||{};Ca(g,{type:"text/javascript",charset:"UTF-8"});rb(e,g);Qa(e,a);ye(c).appendChild(e);return f}function ye(a){var b;return(b=(a||document).getElementsByTagName("HEAD"))&&b.length!==0?b[0]:a.documentElement}function je(){if(this&&this.X){var a=this.X;a&&a.tagName=="SCRIPT"&&we(a,!0,this.R)}}
function we(a,b,c){c!=null&&w.clearTimeout(c);a.onload=function(){};a.onerror=function(){};a.onreadystatechange=function(){};b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}function xe(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);E.call(this,c);this.code=a}B(xe,E);var ze=ma(["https://apis.google.com/js/client.js?onload=",""]);function Ae(a){this.h=a}la(Ae,kd);Ae.prototype.g=function(){return new this.h};
function Be(a){this.h=a;var b=b||{};this.j=b.firebaseEndpoint||"https://www.googleapis.com/identitytoolkit/v3/relyingparty/";this.u=b.identityPlatformEndpoint||"https://identitytoolkit.googleapis.com/v2/";this.m=b.firebaseTimeout||Ce;a=b.firebaseHeaders||De;b={};for(var c in a)b[c]=a[c];this.l=b;c=cd()=="Node";c=w.XMLHttpRequest||c&&firebase.INTERNAL.node&&firebase.INTERNAL.node.XMLHttpRequest;if(!c&&!bd())throw new C("internal-error","The XMLHttpRequest compatibility library was not found.");this.g=
void 0;bd()?this.g=new ee({ma:self}):(a=cd(),a==="ReactNative"||a==="Node"?this.g=new Ae(c):this.g=new nd);this.i=null}var Ee;function Fe(a,b,c,d,e,g,f){Wc()||bd()?a=A(a.v,a):(Ee||(Ee=new O(function(h,k){Ge(h,k)})),a=A(a.o,a));a(b,c,d,e,g,f)}
Be.prototype.v=function(a,b,c,d,e,g){if(bd()&&(typeof w.fetch==="undefined"||typeof w.Headers==="undefined"||typeof w.Request==="undefined"))throw new C("operation-not-supported-in-this-environment","fetch, Headers and Request native APIs or equivalent Polyfills must be available to support HTTP requests from a Worker environment.");var f=new qd(this.g);if(g){f.v=Math.max(0,g);var h=setTimeout(function(){f.dispatchEvent("timeout")},g)}Mb(f,"complete",function(){h&&clearTimeout(h);var k=null;try{k=
JSON.parse(Bd(this))||null}catch(l){k=null}b&&b(k)});Sb(f,"ready",function(){h&&clearTimeout(h);this.dispose()});Sb(f,"timeout",function(){h&&clearTimeout(h);this.dispose();b&&b(null)});ud(f,a,c,d,e)};function Ge(a,b){if(((window.gapi||{}).client||{}).request)a();else{w[He]=function(){((window.gapi||{}).client||{}).request?a():b(Error("CORS_UNSUPPORTED"))};var c=qb(ze,He);pe(ve(c),function(){b(Error("CORS_UNSUPPORTED"))})}}
Be.prototype.o=function(a,b,c,d,e){var g=this;qc(Ee.then(function(){window.gapi.client.setApiKey(g.h);var f=window.gapi.auth.getToken();window.gapi.auth.setToken(null);window.gapi.client.request({path:a,method:c,body:d,headers:e,authType:"none",callback:function(h){window.gapi.auth.setToken(f);b&&b(h)}})}),function(f){b&&b({error:{message:f&&f.message||"CORS_UNSUPPORTED"}})})};
function Ie(a,b,c,d,e,g,f){var h=T(b+c);h.h.set("key",a.h);f&&h.h.set("cb",Date.now().toString());var k=d=="GET";if(k)for(var l in e)e.hasOwnProperty(l)&&h.h.set(l,e[l]);return new O(function(m,x){Fe(a,h.toString(),function(q){if(q)if(q.error){a:{var t=g||{};var z=(q.error&&q.error.errors&&q.error.errors[0]||{}).reason||"";var D={keyInvalid:"invalid-api-key",ipRefererBlocked:"app-not-authorized"};if(z=D[z]?new C(D[z]):null)q=z;else{z=q.error&&(q.error.reason||q.error.message)||"";D={INVALID_CUSTOM_TOKEN:"invalid-custom-token",
CREDENTIAL_MISMATCH:"custom-token-mismatch",MISSING_CUSTOM_TOKEN:"internal-error",INVALID_IDENTIFIER:"invalid-email",MISSING_CONTINUE_URI:"internal-error",INVALID_EMAIL:"invalid-email",INVALID_PASSWORD:"wrong-password",USER_DISABLED:"user-disabled",MISSING_PASSWORD:"internal-error",EMAIL_EXISTS:"email-already-in-use",PASSWORD_LOGIN_DISABLED:"operation-not-allowed",INVALID_IDP_RESPONSE:"invalid-credential",INVALID_PENDING_TOKEN:"invalid-credential",FEDERATED_USER_ID_ALREADY_LINKED:"credential-already-in-use",
MISSING_OR_INVALID_NONCE:"missing-or-invalid-nonce",INVALID_MESSAGE_PAYLOAD:"invalid-message-payload",INVALID_RECIPIENT_EMAIL:"invalid-recipient-email",INVALID_SENDER:"invalid-sender",EMAIL_NOT_FOUND:"user-not-found",RESET_PASSWORD_EXCEED_LIMIT:"too-many-requests",EXPIRED_OOB_CODE:"expired-action-code",INVALID_OOB_CODE:"invalid-action-code",MISSING_OOB_CODE:"internal-error",INVALID_PROVIDER_ID:"invalid-provider-id",CREDENTIAL_TOO_OLD_LOGIN_AGAIN:"requires-recent-login",INVALID_ID_TOKEN:"invalid-user-token",
TOKEN_EXPIRED:"user-token-expired",USER_NOT_FOUND:"user-token-expired",CORS_UNSUPPORTED:"cors-unsupported",DYNAMIC_LINK_NOT_ACTIVATED:"dynamic-link-not-activated",INVALID_APP_ID:"invalid-app-id",TOO_MANY_ATTEMPTS_TRY_LATER:"too-many-requests",WEAK_PASSWORD:"weak-password",PASSWORD_DOES_NOT_MEET_REQUIREMENTS:"password-does-not-meet-requirements",OPERATION_NOT_ALLOWED:"operation-not-allowed",USER_CANCELLED:"user-cancelled",CAPTCHA_CHECK_FAILED:"captcha-check-failed",INVALID_APP_CREDENTIAL:"invalid-app-credential",
INVALID_CODE:"invalid-verification-code",INVALID_PHONE_NUMBER:"invalid-phone-number",INVALID_SESSION_INFO:"invalid-verification-id",INVALID_TEMPORARY_PROOF:"invalid-credential",INVALID_TENANT_ID:"invalid-tenant-id",MISSING_APP_CREDENTIAL:"missing-app-credential",MISSING_CODE:"missing-verification-code",MISSING_PHONE_NUMBER:"missing-phone-number",MISSING_SESSION_INFO:"missing-verification-id",QUOTA_EXCEEDED:"quota-exceeded",SESSION_EXPIRED:"code-expired",REJECTED_CREDENTIAL:"rejected-credential",INVALID_CONTINUE_URI:"invalid-continue-uri",
MISSING_ANDROID_PACKAGE_NAME:"missing-android-pkg-name",MISSING_IOS_BUNDLE_ID:"missing-ios-bundle-id",UNAUTHORIZED_DOMAIN:"unauthorized-continue-uri",INVALID_DYNAMIC_LINK_DOMAIN:"invalid-dynamic-link-domain",INVALID_OAUTH_CLIENT_ID:"invalid-oauth-client-id",INVALID_CERT_HASH:"invalid-cert-hash",UNSUPPORTED_TENANT_OPERATION:"unsupported-tenant-operation",TENANT_ID_MISMATCH:"tenant-id-mismatch",ADMIN_ONLY_OPERATION:"admin-restricted-operation",INVALID_MFA_PENDING_CREDENTIAL:"invalid-multi-factor-session",
MFA_ENROLLMENT_NOT_FOUND:"multi-factor-info-not-found",MISSING_MFA_PENDING_CREDENTIAL:"missing-multi-factor-session",MISSING_MFA_ENROLLMENT_ID:"missing-multi-factor-info",EMAIL_CHANGE_NEEDS_VERIFICATION:"email-change-needs-verification",SECOND_FACTOR_EXISTS:"second-factor-already-in-use",SECOND_FACTOR_LIMIT_EXCEEDED:"maximum-second-factor-count-exceeded",UNSUPPORTED_FIRST_FACTOR:"unsupported-first-factor",UNVERIFIED_EMAIL:"unverified-email",API_KEY_SERVICE_BLOCKED:"api-key-service-blocked"};t=t||
{};Ca(D,t);t=(t=z.match(/^[^\s]+\s*:\s*([\s\S]*)$/))&&t.length>1?t[1]:void 0;for(var sd in D)if(z.indexOf(sd)===0){q=new C(D[sd],t);break a}!t&&q&&(t=typeof q==="undefined"?null:JSON.stringify(q));q=new C("internal-error",t)}}x(q)}else m(q);else x(new C("network-request-failed"))},d,k?void 0:JSON.stringify(ed(e)),a.l,a.m.get())})}function Je(a){return Ke(a).then(function(b){return b.authorizedDomains||[]})}function Le(a){return Ke(a).then(function(b){return b.projectId||""})}
function Ke(a){var b=Me,c={};if(!jd(c,b.pa))return oc();var d=!!b.va,e=b.ia||"POST",g;return Q(c).then(b.qa).then(function(){b.ta&&(c.returnSecureToken=!0);b.ra&&a.i&&typeof c.tenantId==="undefined"&&(c.tenantId=a.i);return d?Ie(a,a.u,b.endpoint,e,c,b.aa,b.S||!1):Ie(a,a.j,b.endpoint,e,c,b.aa,b.S||!1)}).then(function(f){g=f;return b.la?b.la(c,g):g}).then(b.sa).then(function(){if(!b.W)return g;if(!(b.W in g))throw new C("internal-error");return g[b.W]})}new fd;
var Ce=new fd,De={"Content-Type":"application/json"},He="__fcb"+Math.floor(Math.random()*1E6).toString(),Me={S:!0,endpoint:"getProjectConfig",ia:"GET"};function Ne(){var a=Oe,b=va||(va=new vb),c=wb(b,"HEAD")[0];if(!c){var d=wb(b,"BODY")[0];c=b.h("HEAD");d.parentNode.insertBefore(c,d)}d=b.h("STYLE");var e=Pa("style",document);e&&d.setAttribute("nonce",e);if(a instanceof Ra)a=a.g;else throw Error("");if(w.trustedTypes)if("textContent"in d)d.textContent=a;else if(d.nodeType==3)d.data=String(a);else if(d.firstChild&&d.firstChild.nodeType==3){for(;d.lastChild!=d.firstChild;)d.removeChild(d.lastChild);d.firstChild.data=String(a)}else{for(;e=d.firstChild;)d.removeChild(e);
d.appendChild((d.nodeType==9?d:d.ownerDocument||d.document).createTextNode(String(a)))}else d.innerHTML=a;b.i(c,d)};var Sa=ma(["body{margin:0}.firebase-container{background-color:#fff;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;color:rgba(0,0,0,.87);direction:ltr;font:16px Roboto,arial,sans-serif;margin:0 auto;max-width:360px;overflow:hidden;padding-top:8px;position:relative;width:100%}@media (max-width:520px){.firebase-container{box-shadow:none;max-width:none;width:100%}}"]),Oe=new Ra;w.document.readyState=="complete"?(Ne(),Pe()):Kb(window,"load",function(){Ne();Pe()});
function Pe(){Q().then(function(){var a=Rc(T(w.window&&w.window.location.href||self&&self.location&&self.location.href||""),"link");if(a&&Qe(a))return Re(a).then(function(b){if(b){b=w.window;var c="about:blank";if(a){var d=d===void 0?Ma:d;a:if(d=d===void 0?Ma:d,a instanceof G)d=a;else{for(c=0;c<d.length;++c){var e=d[c];if(e instanceof La&&e.ja(a)){d=new G(a);break a}}d=void 0}d=d||Ka;if(d instanceof G)c=d.g;else throw Error("");}b.location.href=c}else return Se()},function(){return Se()});gd("Request is missing required data.");
return Se()})}
function Re(a){var b=Rc(T(a),"apiKey"),c=new Be(b);return qc(qc(Je(c),function(d){gd("Unable to verify that the app domain is authorized.");throw d;}).then(function(d){return Zc(d,a)?Dd().then(function(e){return e.apiKey&&b===e.apiKey?Q(!0):Je(new Be(e.apiKey)).then(function(g){if(Zc(g,a))return Q(!0);gd("App domain is unauthorized in the Firebase Hosting project.");return Q(!1)},function(){return Le(c).then(function(g){return e.messagingSenderId&&e.messagingSenderId!==g?Q(!1):Q(!0)},function(g){throw g;
})})},function(){return Q(!0)}):(gd("App domain is unauthorized"),Q(!1))}),function(){return Q(!1)})}function Qe(a){return a?(a=T(a),!(!(Rc(a,"apiKey")&&Rc(a,"mode")&&Rc(a,"oobCode"))||a.i!="http"&&a.i!="https")):!1}function Se(){return ad().then(function(){(new de("The operation is not valid.")).render(document.body)})};
